# Use postgres/example user/password credentials
version: '3.1'

services:
  jaeger:
    image: jaegertracing/all-in-one
    restart: unless-stopped
    ports:
      - 16686:16686
      - 4317:4317

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - 5432:5432 

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080

  hzpp_delay_stats:
    image: kronicaler/hzpp_delay_stats
    container_name: hzpp_delay_stats
    environment:
      - OTLP_ENDPOINT=
      - DATABASE_URL=mysql://root:${DB_PASS}@mariadb/markov_bot
      - RUST_LOG=error,hzpp_delay_stats=info
    build:
      context: ./
      dockerfile: dockerfile
    restart: unless-stopped