# Use postgres/example user/password credentials
version: '3.1'

services:
  jaeger:
    image: jaegertracing/all-in-one
    restart: unless-stopped
    ports:
      - 16687:16686

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: hzpostgres
      POSTGRES_DB: hzpp
    volumes:
      - ./postgres:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080

  hzpp_delay_stats:
    image: kronicaler/hzpp_delay_stats
    container_name: hzpp_delay_stats
    environment:
      - OTLP_ENDPOINT=http://jaeger:4317
      - DATABASE_URL=postgresql://postgres:hzpostgres@db/hzpp
      - RUST_LOG=error,hzpp_delay_stats=info
    build:
      context: ./
      dockerfile: dockerfile
    restart: unless-stopped