openapi: 3.0.0
info:
  title: HZPP Planer API
  version: 1.0.0

paths:
  /hzpp/planer/v3/getRoutes.php:
    get:
      summary: Get Routes
      parameters:
        - name: date
          in: query
          required: true
          schema:
            type: string
          example: "20230823"
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              example: |
                [
                  {
                    "route_id": "i-tr146au",
                    "route_number": 2010,
                    "route_src": "Tovarnik",
                    "route_desc": "Zagreb Glavni kolodvor",
                    "arrival_time": "03:38:00",
                    "departure_time": "03:39:00",
                    "bikes_allowed": 1,
                    "wheelchair_accessible": 2,
                    "route_type": 2,
                    "stops": [
                      {
                        "stop_id": "i-o410",
                        "stop_name": "Vinkovci",
                        "arrival_time": "03:31:00",
                        "departure_time": "03:31:00",
                        "latitude": 45.300398403,
                        "longitude": 18.8028085306,
                        "sequence": 1
                      },
                      {
                        "stop_id": "i-o405",
                        "stop_name": "Ivankovo",
                        "arrival_time": "03:38:00",
                        "departure_time": "03:39:00",
                        "latitude": 45.2784122464,
                        "longitude": 18.6674795808,
                        "sequence": 2
                      },
                      {
                        "stop_id": "i-o406",
                        "stop_name": "Vođinci",
                        "arrival_time": "03:42:00",
                        "departure_time": "03:42:00",
                        "latitude": 45.2696813929,
                        "longitude": 18.6137668509,
                        "sequence": 3
                      }
                    ],
                    "calendar": [
                      {
                        "monday": 1,
                        "tuesday": 1,
                        "wednesday": 1,
                        "thursday": 1,
                        "friday": 1,
                        "saturday": 0,
                        "sunday": 0
                      },
                      {
                        "monday": 0,
                        "tuesday": 0,
                        "wednesday": 0,
                        "thursday": 0,
                        "friday": 0,
                        "saturday": 1,
                        "sunday": 0
                      }
                    ]
                  }
                ]

  /hzpp/planer/v3/getStops.php:
    get:
      summary: Get Stations
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              example: |
                [
                  {
                    "stop_id": "i-o432",
                    "stop_code": 71402,
                    "stop_name": "Andrijaševci",
                    "stop_lat": 45.2300143755,
                    "stop_lng": 18.7305206475
                  },
                  {
                    "stop_id": "i-o557",
                    "stop_code": 72802,
                    "stop_name": "Andrijevci",
                    "stop_lat": 45.1907748793,
                    "stop_lng": 18.2928904688
                  },
                  {
                    "stop_id": "i-o444",
                    "stop_code": 71506,
                    "stop_name": "Antunovac",
                    "stop_lat": 45.4835931019,
                    "stop_lng": 18.6701419477
                  }
                ]

  /hzpp/planer/v3/getConnectionLinks.php:
    get:
      summary: Get Connection Links
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              example: |
                [
                  {
                    "stop_name": "Banova Jaruga",
                    "waiting_route_number": 541,
                    "route_number": 2411,
                    "waiting_minutes": 10
                  },
                  {
                    "stop_name": "Banova Jaruga",
                    "waiting_route_number": 542,
                    "route_number": 2411,
                    "waiting_minutes": 10
                  },
                  {
                    "stop_name": "Banova Jaruga",
                    "waiting_route_number": 546,
                    "route_number": 2457,
                    "waiting_minutes": 5
                  },
                  {
                    "stop_name": "Banova Jaruga",
                    "waiting_route_number": 2013,
                    "route_number": 2451,
                    "waiting_minutes": 10
                  }
                ]

  /hzpp/planer/v3/getCompositions.php:
    get:
      summary: Get Compositions
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              example: |
                [
                  {
                    "id": "3",
                    "name": "DD MD",
                    "title": "Wagon MDDlm series",
                    "description": "– four-axle wagons intended for the carriage of tracked cars\r\n– internal and international traffic\r\n– Maximum speed: 120 km/h",
                    "images": []
                  },
                  {
                    "id": "1",
                    "name": "6111",
                    "title": "Electric train 6 111",
                    "description": "Electric train series 6 111 - \"Hungarian\"\r\n- maximum speed: 120 km/h\r\n- power: 1.2 MW\r\n- thyristor regulation\r\n- VOITH axle transmission\r\n- KONČAR electric traction motors\r\n- 136/236 seats\r\n- production: Ganz M",
                    "images": [
                      {
                        "picture_url": "http://www.hzpp.hr/Media/Default/_Profiles/7823f8ab/3a18ba12/4a_4107%20vr.jpg?v=636780598840709531"
                      },
                      {
                        "picture_url": "http://www.hzpp.hr/Media/Default/_Profiles/7823f8ab/3a18ba12/4b_4103%20vr.jpg?v=636780598838990768"
                      },
                      {
                        "picture_url": "http://www.hzpp.hr/Media/Default/_Profiles/7823f8ab/3a18ba12/6111r.jpg?v=636780598842115745"
                      }
                    ]
                  }
                ]
